name: Pipeline DevSecOps

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Bandit
      run: |
        pip install bandit

    - name: Run Bandit
      run: |
        bandit -r .

    - name: Build and Test
      run: |
        python setup.py build
        python setup.py test
